# LoopFlow — Configuración de Base de Datos MySQL
db.driver=com.mysql.cj.jdbc.Driver
db.url=jdbc:mysql://butgun1czqnu3q5ju3up-mysql.services.clever-cloud.com:3306/butgun1czqnu3q5ju3up
db.user=uedpcdcqst4ekgsp
db.password=L4hPAxdCb06b7opX22qE
